src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/model/translator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/RestrictedPatientService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/model/TranslatorTest.kt
- SDIT-405: ♻️ Correct restricted patient name
=> SDIT-405: ♻️ Correct restricted patient name

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IndexQueueService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PrisonerSynchroniserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/model/IndexStatusTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/model/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/model/SyncIndexTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IndexQueueServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IndexStatusServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PrisonerSynchroniserServiceTest.kt, src/test/resources/application-test.yml
- SDIT-405: ✅ More tests copied from probation indexer
=> SDIT-405: ✅ More tests copied from probation indexer

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/MaintainIndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PopulateIndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PrisonerSynchroniserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/repository/PrisonerRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/MaintainIndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PopulateIndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PrisonerSynchroniserServiceTest.kt
SDIT-405: ♻️ Refactor prisoner synchroniser to be just about the individual prisoners
=> SDIT-405: ♻️ Refactor prisoner synchroniser to be just about the individual prisoners

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/PrisonerSynchroniserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/RestrictedPatientService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/integration/wiremock/IncentivesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/integration/wiremock/RestrictedPatientApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/IncentivesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearchindexer/services/RestrictedPatientsServiceTest.kt, src/test/resources/restricted-patients/mappings/getRestrictedPatient_A123ZZZ.json, src/test/resources/restricted-patients/mappings/getRestrictedPatient_A7090BF.json, src/test/resources/restricted-patients/mappings/getRestrictedPatient_A9999RA.json, src/test/resources/restricted-patients/mappings/getRestrictedPatient_A9999RB.json, src/test/resources/restricted-patients/mappings/getRestrictedPatient_A9999RC.json, src/test/resources/restricted-patients/mappings/getRestrictedPatient_not_found.json
SDIT-405: ♻️  Improve restricted patients service and test
=> SDIT-405: ♻️  Improve restricted patients service and test

hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/config/GsonConfig.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerSearchResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonSearch.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonerListCriteria.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonerSearchService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/ReleaseDateSearch.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/SearchCriteria.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PaginationRequest.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PhysicalDetailRequest.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PossibleMatchCriteria.kt
Prisoner search files pulled in from prisoner-offender-search (and modified for opensearch)
=> SDIT-937 Add prisoner-search files

hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/config/HmppsPrisonerSearchExceptionHandler.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PhysicalDetailResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerDetailResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerKeywordResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerMatchResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonersInPrisonResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/RestrictedPatientSearchResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/KeywordService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/MatchService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PhysicalDetailService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonerDetailService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonersInPrisonService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/RestrictedPatientSearchCriteria.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/RestrictedPatientSearchService.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/KeywordRequest.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/MatchRequest.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PrisonerDetailRequest.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PrisonerMatch.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PrisonerMatches.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PrisonersInPrisonRequest.kt
The majority of this PR is a lift-and-shift (with updates for opensearch) + added in the missing ExceptionHandler
=> SDIT-937 Add controller and services for search files

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/PopulateIndexListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexQueueService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/RefreshIndexService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexQueueServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/RefreshIndexServiceTest.kt
- SDIT-1062: ✨ Add in new refresh page of prisoners
- SDIT-1062: ✨ Add in new refresh prisoners index message creation
=> SDIT-1062: ✨ Add in new refresh prisoners index message creation

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/config/ApplicationInsightsConfiguration.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/MaintainIndexService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/MaintainIndexServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt
SDIT-1130: ✨ Improve app insights events
=> SDIT-1130: ✨ Improve app insights events

hmpps-prisoner-search-indexer/helm_deploy/hmpps-prisoner-search-indexer/Chart.yaml, hmpps-prisoner-search-indexer/helm_deploy/hmpps-prisoner-search-indexer/values.yaml, hmpps-prisoner-search/helm_deploy/hmpps-prisoner-search/Chart.yaml, hmpps-prisoner-search/helm_deploy/hmpps-prisoner-search/values.yaml, hmpps-prisoner-search/helm_deploy/values-preprod.yaml, hmpps-prisoner-search/helm_deploy/values-prod.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
4 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
=> Migrating project to use groups in allowlist

hmpps-prisoner-search-indexer/helm_deploy/values-preprod.yaml, hmpps-prisoner-search/helm_deploy/values-preprod.yaml
Reverts ministryofjustice/hmpps-prisoner-search#304
=> Revert "SDIT-1646: 🔧 Turn off pre-prod overnight and at weekends"

hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/SearchClient.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/SearchClientTest.kt
=> SDIT-1644 500 errors returned from prisoner search

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/dto/nomis/OffenderBooking.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestServiceIntTest.kt
Because sometimes it does, sometimes it doesn't.
=> SDIT-1679 Don't produce a diff if old endpoint returns null ADA

hmpps-prisoner-search-indexer/helm_deploy/values-dev.yaml, hmpps-prisoner-search-indexer/helm_deploy/values-preprod.yaml, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NomisService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestServiceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NomisServiceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/PrisonApiMockServer.kt
This reverts commit 13dfb0bdaedb49eb57112fc87f4f5893e41123b6.
=> Revert "SDIT-1617 Try out the new prison-api endpoint for real (#333)"

hmpps-prisoner-search-indexer/helm_deploy/values-dev.yaml, hmpps-prisoner-search-indexer/helm_deploy/values-preprod.yaml, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NomisService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestServiceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NomisServiceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/PrisonApiMockServer.kt
This reverts commit 48b79014d160cbdb07276803f0ea52167bb60afe.
=> Revert "SDIT-1617 Try out the new prison-api endpoint for real (#335)"

hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/config/OpenApiConfiguration.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/GlobalSearchResource.kt, hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerSearchResource.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/AbstractSearchIntegrationTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/GlobalSearchResourceTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/OpenApiDocsTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerSearchByPrisonerNumbersResourceTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerSearchResourceTest.kt
created new role following hmpps role standards for core person records
=> CPR-346-add-role

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt
Fix issue where integration tests fire receive event when recreating prisoners
=> SDIT-1933 Raise "receive" event for move booking

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt, common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/PrisonerAlias.kt, common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt, common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/nomis/Alias.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/CompareIndexResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceServiceTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/model/ObjectBuilder.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/model/PrisonerModelIntTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchFieldsIntegrationTest.kt
As requested by CPR team.
Kept the slightly awkward "raceCode" name as used by prison-api
=> SDIT-1934 ethnicity code to main record and alias

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/health/IndexInfo.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/CompareIndexResource.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/CompareIndexService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/CompareIndexResourceIntTest.kt
Move detailed red index comparison to a new prisoner endpoint
=> SDIT-1957 Update the new index using partial updates instead of an overall save

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventEmitter.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt
Updated domain events to include person reference as per https://dsdmoj.atlassian.net/wiki/spaces/NDSS/pages/3732570166/ADR+-+Domain+Event+Schema
=> MIC-615 add person reference to domain events

hmpps-prisoner-search-indexer/helm_deploy/hmpps-prisoner-search-indexer/restore.sh
Copy the new index to preprod alongside the existing blue and green indices
=> SDIT-2102 Add RED index to the refresh from prod

hmpps-prisoner-search-indexer/helm_deploy/hmpps-prisoner-search-indexer/restore.sh
Fix possible timeout due to longer restore time
=> SDIT-2102 Add RED index to the refresh from prod - fix

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
refactor of setRestrictedPatient()
=> SDIT-2176 Move restricted patients to domain partial update - minor refactor

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/AlertsUpdatedEventService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
Simulate sending of domain events as a result of red index updates.
=> Sdit 2182 create duplicate logging from the red index updates

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/AlertsUpdatedEventService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
Reverts ministryofjustice/hmpps-prisoner-search#453
=> Revert "Sdit 2182 create duplicate logging from the red index updates"

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepository.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepositoryTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
prisoner creation in opensearch needs to check it does not already exist
=> SDIT-2182 Create duplicate logging from the red index updates - handle create

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/OffenderEventQueueService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/OffenderEventQueueServiceTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/AbstractSearchIntegrationTest.kt, hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/model/ObjectBuilder.kt
=> SDIT-2077 Unnecessary exception logging noise needs removing

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/OffenderEventQueueService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/OffenderEventQueueServiceTest.kt
Correct the Exception type for create errors
=> SDIT-2077 Unnecessary exception logging noise needs removing - fix

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/DomainEventsResource.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/AlertsUpdatedEventService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/ConvictedStatusEventService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventEmitter.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerDifferenceServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/AlertsUpdatedEventServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/ConvictedStatusChangedEventServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventServiceTest.kt
Centralise all the 'if red' logic into one class and include the simulated event message details for more comprehensive comparison.
=> SDIT-2638 Refactor and tidy RED event simulation telemetry

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventPublisherListenerTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/DomainEventsResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt
Some domain event creation was missing for a difference found during an index refresh
=> SDIT-2620 Remove old index code - refresh event fix

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt, common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt
Temporary change to experiment with a new field
=> SDIT-2645 Avoid event creation when a new field is added

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/AlertsService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/AlertsServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/AlertsApiMockServer.kt
- Switch to person.alerts.changed event
- Impose explicit order on alert list
=> SDIT-2177-Move-alerts-to-domain-partial-update-2

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListener.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt
Fix to correct the alert message format - no additionalInformation
=> SDIT-2177 Move alerts to domain partial update 2 - fix

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt
Fix to remove @DiffableProperty for new field
=> SDIT-2724 Add admission date and complexity of needs fields to prisoner search document - fix

hmpps-prisoner-search-indexer/build.gradle.kts, hmpps-prisoner-search-indexer/helm_deploy/values-dev.yaml, hmpps-prisoner-search-indexer/helm_deploy/values-preprod.yaml, hmpps-prisoner-search-indexer/helm_deploy/values-prod.yaml, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/config/CacheConfig.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/config/WebClientConfiguration.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/health/HealthCheck.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/MaintainIndexService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonRegisterService.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt, hmpps-prisoner-search-indexer/src/main/resources/application-dev.yml, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/health/HealthCheckIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/model/OffenderBookingBuilder.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt, hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/PrisonRegisterMockServer.kt, hmpps-prisoner-search-indexer/src/test/resources/application-test.yml
Use prison register and OUT status to limit complexity-of-need calls
=> SDIT-2724-Add-admission-date-and-complexity-of-needs-fields-to-prisoner-search-document---CNL-performance-fix

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/PersonalCareNeed.kt, hmpps-prisoner-search-indexer/Dockerfile, hmpps-prisoner-search/Dockerfile, hmpps-prisoner-search/src/test/resources/prisoners/prisonerA7089EY.json, hmpps-prisoner-search/src/test/resources/results/globalSearch/get_prisoner_A7089EY.json
Add Date annotation to PersonalCareNeed dates
=> SDIT-2742 Add care needs, smoking and languages fields to prisoner-search fix2

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt
Add DiffableProperty annotation to care needs, smoking and languages fields
=> SDIT-2742 Add care needs, smoking and languages fields to prisoner-search add DiffableProperty

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/config/CacheConfig.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepository.kt, hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonRegisterService.kt
Cache should expire, not be indefinite
=> SDIT-2724-Add-admission-date-and-complexity-of-needs-fields-to-prisoner-search-document---Cache-fix

common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt, common/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/TranslatorTest.kt
Add 'merged' to identifier types
=> SDIT-2883 Make Prisoner Merge History Available

hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt
Add detailed logging of the EVENTS_UNKNOWN_MOVEMENT event
=> SDIT-2941 Receive event not occurring after booking.moved
