ministryofjustice/hmpps-prisoner-search

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/PrisonerDifferencesResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/config/OpenApiConfiguration.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/GlobalSearchResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PhysicalDetailResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerDetailResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerKeywordResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerMatchResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonersInPrisonResource.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/OpenApiDocsTest.kt
In [HMPPS Integration API](https://github.com/ministryofjustice/hmpps-integration-api), we create simulators based on an upstream API's OpenAPI spec using [Prism](https://stoplight.io/open-source/prism) for our smoke tests. Recently we noticed it was failing.
Upon investigation, we realised that security requirements for endpoints within Prisoner Offender Search referred to security schemes that don't exist. This meant that in the Swagger Docs, no "available authorizations" showed for the
endpoint and the OpenAPI spec JSON was invalid (checked by copying it into [Swagger Editor](https://editor.swagger.io/)).
It seems a [recent change in Prism](https://github.com/stoplightio/prism/blob/master/CHANGELOG.md#540-20231009) meant that it doesn't like when invalid [security …
> HIA-553: 🐛 Fix invalid Swagger docs security schemes for endpoints

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventPublisherListener.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventEmitter.kt
- hmpps-prisoner-search-indexer/src/main/resources/application.yml
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterTest.kt
- hmpps-prisoner-search-indexer/src/test/resources/application-test.yml
- OpenSearch is updated automatically after a document update but is not flushed to disk, therefore, by the time a domain event is raised indicating that the datastore has been updated can be published before changes are flushed, therefore call backs using the search API can retrieve stale results
- OpenSearch does flush changes every 1 second so by delaying the publish by at least 1 second should guarantee updates have been flushed by the time clients receive the associated domain events
> SDIT-1361 Delay sending all domain events by 2 seconds

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/AttributeSearchResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchService.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/AttributeSearchRequest.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/BooleanMatcher.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/DateMatcher.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/DateTimeMatcher.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/IntMatcher.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/Query.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/StringMatcher.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/TypeMatcher.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/AttributeSearchResourceTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchServiceTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/dto/AttributeSearchRequestJsonTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/dto/AttributeSearchRequestTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/dto/StringMatcherTest.kt
The example above has the old `queries` list - I've changed that with another commit but can't be bothered with more screen shots.
> SDIT-1490 Add Open API docs and limit to single top level query

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventPublisherListener.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventPublisherListenerTest.kt
- hmpps-prisoner-search-indexer/src/test/resources/application-test.yml
By doing the join and therefore waiting for the publish() result, any errors are thrown which means they will be retired and eventually move to DLQ
> SDIT-1509 await publish so that any errors are thrown

- hmpps-prisoner-search/helm_deploy/values-dev.yaml
- hmpps-prisoner-search/helm_deploy/values-preprod.yaml
- hmpps-prisoner-search/helm_deploy/values-prod.yaml
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/config/WebClientConfiguration.kt
- hmpps-prisoner-search/src/main/resources/application-dev.yml
- hmpps-prisoner-search/src/main/resources/application.yml
- hmpps-prisoner-search/src/test/resources/application-test.yml
And it means you can do things like [this](https://github.com/ministryofjustice/hmpps-prisoner-to-nomis-update/blob/main/helm_deploy/values-prod.yaml#L12) and [this](https://github.com/ministryofjustice/hmpps-prisoner-to-nomis-update/blob/main/src/test/resources/application-test.yml#L8). Which are easier to digest.
> SDIT-1336 Go back to old api URL properties - it's established and it works fine

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/DateTimeMatcher.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/DateTimeMatcherTest.kt
DateTimeMatcher tests intermittently failed when the time had zero seconds because it was being truncated as per the LocalDateTime.toString() Javadocs:
```
The output will be one of the following ISO-8601 formats:
uuuu-MM-dd'T'HH:mm
uuuu-MM-dd'T'HH:mm:ss
uuuu-MM-dd'T'HH:mm:ss.SSS
uuuu-MM-dd'T'HH:mm:ss.SSSSSS
uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSS
The format used will be the shortest that outputs the full value of the time where the omitted parts are implied to be zero.
```
> SDIT-1561 Fix bug with times on zero seconds

- .circleci/continue_config.yml
- hmpps-prisoner-search/build.gradle.kts
Split out attribute search tests from the other tests and run them in parallel.
> SDIT-1561 Try out parallel search tests

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/StringMatcher.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchIntegrationTest.kt
All string searches should be case-insensitive. String contains searches should allow single character (?) and multi-character (*) wildcards.
> SDIT-1561 String searches fine tuning

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AtttributeResolver.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/Query.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PhysicalDetailResourceTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeResolverTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchIntegrationTest.kt
Found a bug while testing searching on physical details - if you search for prisoners with both `tattoos.bodyPart=Arm` and `tattoos.comment=dragon` then you're asking for prisoners with a tattoo of a dragon on their arm. However you also receive anyone with 2 tattoos, one on their arm and the other of a dragon. This is because the BodyPartDetails class does not have the `@Field(type = FieldType.Nested)` annotation, meaning that [OpenSearch flattens the fields](https://opensearch.org/docs/latest/field-types/supported-field-types/nested/#flattened-form) and loses any connection between `tattoo.bodyPart` and `tattoo.comment`.
First I've updated the tests for `alerts` (which is already nested) to highlight the bug - and fixed that bug in the query builders by using a NestedQuery.
Next job …
> SDIT-1561 Handle lists of nested objects

- common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/model/translator.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/model/TranslatorTest.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PhysicalDetailService.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/ReferenceDataService.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PhysicalDetailRequest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/model/ObjectBuilder.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/model/nomis/dto/translator.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PhysicalDetailResourceTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/ReferenceDataResourceTest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchFieldsIntegrationTest.kt
In NOMIS there appears to be no quantifiable difference between `marks` and `otherMarks` - but leaving them separate means they have to be searched for individually. Instead we will delete `otherMarks` and consolidate them into `marks`. It should be safe to delete `otherMarks` because a) it's nullable and b) no clients are referencing the field anyway (except in test JSON).
We've also noticed that there are a lot of comments in `marks` and `otherMarks` which include either "tattoo" or "scar" but both NOMIS and prisoner search have dedicated storage for `tattoos` and `scars`. This makes it hard to search for a tattoo or a scar - you'd need to check marks too. To make the search easier we've decided to copy any marks with comments including "tattoo" or "scar" into the relevant prisoner …
> SDIT-1561 Remove otherMarks from the Prisoner record

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/StringMatcher.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchIntegrationTest.kt
Otherwise the fuzzy query will find partial matches on the search term but we want a full match
> SDIT-1561 Don't perform fuzzy query for wildcards

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/model/translator.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NomisService.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/dto/nomis/OffenderBookingOld.kt
The new prison-api endpoint we will be calling to populate the Prisoner record has a slightly different model (mainly because it was returning the current booking offence history just to calculate most serious offence - but we're going to be adding the entire offence history for all bookings soon so I wanted to remove that).
As an intermediary step we're moving over to the new model early. This will make it easier to test the old and new prison-api endpoints.
> SDIT-1583 Switch to the model returned by the new prison-api endpoint

- hmpps-prisoner-search-indexer/helm_deploy/values-dev.yaml
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestService.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/dto/nomis/OffenderBooking.kt
- hmpps-prisoner-search-indexer/src/main/resources/application.yml
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/CompareIndexResourceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/MaintainIndexResourceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/NewOffenderEndpointTestServiceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/PrisonApiMockServer.kt
- hmpps-prisoner-search-indexer/src/test/resources/application-test.yml
Every time we write a Prisoner record to Opensearch, we will call the new prison-api endpoint to make sure it returns the same details as the old one and publish telemetry if not. This is to gain confidence that the new endpoint works the same as the old one before switching to the new endpoint.
> SDIT-1583 Test new prison-api endpoint in dev

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/AttributeSearchResource.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/api/StringMatcher.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/attributesearch/AttributeSearchIntegrationTest.kt
Testing highlighted an issue where searching for "firstName CONTAINS s*" finds any names containing an "s", but the intention was for any names starting with "s".
> SDIT-1663 Differentiate between contains and wildcard searches, and document with examples

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventEmitter.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt
- hmpps-prisoner-search-indexer/src/main/resources/swagger-description.html
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventServiceTest.kt
When a new booking is created by mistake the NOMIS user will release and bring the person back on an older booking. This was previously emitting a receive event with a reason off NEW_ADMISSION, this now sets the reason to a new value of READMISSION_SWITCH_BOOKING so clients can distinguish between this scenario and a normal READMISSION
> SDIT-1861 READMISSION_SWITCH_BOOKING for correcting new booking mistakes

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/PrisonerMovementsEventService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/events/HmppsDomainEventsEmitterIntTest.kt
Most integration tests were accidentally setting the bookingId to null even though the data had a booking, this caused additionally domain events throwing off the tests.
So removed hack in code to ignore scenario and corrected the seed data
> SDIT-1934 Fixed integration test and removes hack for move booking

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerIntTest.kt
Remove a duplicate RED update on receipt of a domain event
> SDIT-1957-Update-the-new-index-using-partial-updates-instead-of-an-overall-save

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/config/WebClientConfiguration.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IncentivesService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IncentivesServiceTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/IncentivesApiMockServer.kt
When a failure happens, particularly after a new booking, multiple receive domain events can be raised since we fall back to using previous incentive level - but that value will typically be incorrect for a new booking so "differences" are incorrectly found.
This mitigates by trying a few times before failing.
> SDIT-2041 Retry get incentive level a few times if it fails

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/OffenderEventListenerIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
Reindex RED domain data (e.g. incentives) when the current booking has changed, e.g. when a prisoner is received on an older booking id
> SDIT-2140 Update domains when booking id changes

- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/PrisonerDetailService.kt
- hmpps-prisoner-search/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/services/dto/PrisonerDetailRequest.kt
- hmpps-prisoner-search/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/search/resource/PrisonerDetailResourceTest.kt
Add date of birth as a filter field into the `prisoner-details` endpoint. This will allow HMPPS Integration API to use a search that filters by Prison ID. As a bonus, this increases the parity with the `global-search` API.
> HMAI-66 Add Date of birth to prisoner details

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepository.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepositoryTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
NPE and need to omit RP updates from ordinary prisoner events
> SDIT-2182 Create duplicate logging from the red index updates - fix

- common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/CurrentIncentive.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepositoryTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerServiceTest.kt
Creation of an event was not simulated for prisoner / alias deletion.
Also make the incentive code field non-null.
> SDIT-2182 Create duplicate logging from the red index updates - handle delete

- hmpps-prisoner-search-indexer/SendingMessages.md
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/DomainEventsResource.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexExceptions.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/DomainEventsResourceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt
This covers some of the additional events which are no longer retried automatically when a publish call fails.
> SDIT-2681-Add-emergency-fix-endpoints-for-domain-events

- common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/Prisoner.kt
- common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/model/translator.kt
Reverts ministryofjustice/hmpps-prisoner-search#507
When the index is refreshed, this field does NOT cause any events to be triggered
> Revert "SDIT-2645 Avoid event creation when a new field is added"

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/IntegrationTestBase.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/listeners/DomainEventListenerIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/resource/RefreshIndexResourceIntTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/wiremock/ComplexityOfNeedApiMockServer.kt
Fix for an unexpected feature of CNL event: Need to null the CNL (complexity of need level) field if active = false in the event
> SDIT-2724 Add admission date and complexity of needs fields to prisoner search document - CNL active fix

- common/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/common/nomis/OffenderLanguageDto.kt
language skill indicators can be null in Nomis
> SDIT-2742 Add care needs, smoking and languages fields to prisoner-search fix

- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepository.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerService.kt
- hmpps-prisoner-search-indexer/src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserService.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/repository/PrisonerRepositoryTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/IndexListenerServiceTest.kt
- hmpps-prisoner-search-indexer/src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/indexer/services/PrisonerSynchroniserServiceTest.kt
We now need to know whether a deletion actually deleted a prisoner to avoid multiple prisoner-removed events.
> SDIT-2672 Add handler for Nomis event BOOKING-DELETED - fix
